### PR TITLE
Switch stable to Cowboy

### PR DESCRIPTION
**Pull request by essen**
Part of rabbitmq/rabbitmq-management#236

### CODE REVIEW

**Comment by michaelklishin** [comment]
I'm getting test failures that cannot be reproduced in `stable`.

**Comment by essen** [comment]
Weird, I ran the tests on this one. Will double check.

**Comment by essen** [comment]
The tests pass just fine for me with the current upstream branch. What failures do you see? Perhaps a specific Erlang version is failing?

**Comment by michaelklishin** [comment]
HTTP API responds with 404s to `GET` requests. I will make sure I have cleaned all repos first.

**Comment by michaelklishin** [comment]
I have the same failures as Travis.

**Comment by essen** [comment]
Travis seems to fetch management stable; you need to have management and web-dispatch on the branch rabbitmq-management-236 (which hasn't been merged yet) for this to work.

**Comment by michaelklishin** [comment]
Ah, that makes sense now.

**Pull request merged**
